/*-----------------------------------------------------------------------------
    Name: exit_script
    Generated By: netstorm
    Date of generation: 01/30/2023 11:27:10
    Flow details:
    Build details: 4.10.0 (build# 47)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"

int exit_script()
{
    return 0;
}
